#!/usr/bin/env bash

kao_user_state_require_context() {
  if [ -z "${KROOT:-}" ]; then
    printf 'ERROR: KROOT is required for user state context\n' >&2
    return 1
  fi

  KAO_USER_ENV_DIR="${KROOT}/config"
  KAO_USER_RUNTIME_ENV_FILE="${KAO_USER_ENV_DIR}/user.env"
  KAO_USER_RUNTIME_STATE_FILE="${KAO_USER_ENV_DIR}/user.state"
  KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE="${KAO_USER_ENV_DIR}/user.active.snapshot.env"
  KAO_USER_LOG_DIR="${KROOT}/state/logs"
  KAO_USER_LOG_FILE="${KAO_USER_LOG_DIR}/user.log"
}

kao_user_state_shell_quote() {
  python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "${1:-}"
}

kao_user_state_slug() {
  local raw
  raw="${1:-}"
  raw="$(printf '%s' "${raw}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')"
  raw="${raw#-}"
  raw="${raw%-}"
  if [ -z "${raw}" ]; then
    raw="unknown"
  fi
  printf '%s' "${raw}"
}

kao_user_state_now() {
  date '+%Y-%m-%d %H:%M:%S'
}

kao_user_state_log() {
  local message
  message="${1:-}"

  kao_user_state_require_context || return 1
  mkdir -p "${KAO_USER_LOG_DIR}"

  printf '%s | %s\n' "$(kao_user_state_now)" "${message}" >> "${KAO_USER_LOG_FILE}"
}

kao_user_state_allowed_fields() {
  printf '%s\n' \
    "KAO_USER_NAME" \
    "KAO_USER_ROLE" \
    "KAO_USER_ID" \
    "KAO_USER_TITLE" \
    "KAO_USER_HANDLE" \
    "KAO_USER_ORG"
}

kao_user_state_is_allowed_field() {
  local target
  target="${1:-}"

  case "${target}" in
    KAO_USER_NAME|KAO_USER_ROLE|KAO_USER_ID|KAO_USER_TITLE|KAO_USER_HANDLE|KAO_USER_ORG)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

kao_user_state_normalize_field_name() {
  local raw
  raw="$(printf '%s' "${1:-}" | tr '[:lower:]' '[:upper:]')"

  case "${raw}" in
    NAME|KAO_USER_NAME) printf 'KAO_USER_NAME' ;;
    ROLE|KAO_USER_ROLE) printf 'KAO_USER_ROLE' ;;
    ID|USER_ID|KAO_USER_ID) printf 'KAO_USER_ID' ;;
    TITLE|KAO_USER_TITLE) printf 'KAO_USER_TITLE' ;;
    HANDLE|KAO_USER_HANDLE) printf 'KAO_USER_HANDLE' ;;
    ORG|ORGANIZATION|KAO_USER_ORG) printf 'KAO_USER_ORG' ;;
    *) printf '%s' "${raw}" ;;
  esac
}

kao_user_state_default_runtime_exports() {
  local name role user_id title handle org
  name="${1:-runtime user}"
  role="${2:-operator user}"
  user_id="${3:-}"
  title="${4:-not set}"
  handle="${5:-not set}"
  org="${6:-not set}"

  if [ -z "${user_id}" ]; then
    user_id="user-$(kao_user_state_slug "${name}")"
  fi

  printf 'KAO_USER_NAME=%s\n' "$(kao_user_state_shell_quote "${name}")"
  printf 'KAO_USER_ROLE=%s\n' "$(kao_user_state_shell_quote "${role}")"
  printf 'KAO_USER_ID=%s\n' "$(kao_user_state_shell_quote "${user_id}")"
  printf 'KAO_USER_TITLE=%s\n' "$(kao_user_state_shell_quote "${title}")"
  printf 'KAO_USER_HANDLE=%s\n' "$(kao_user_state_shell_quote "${handle}")"
  printf 'KAO_USER_ORG=%s\n' "$(kao_user_state_shell_quote "${org}")"
}

kao_user_state_write_canonical_env() {
  local env_file generator_label name role user_id title handle org
  env_file="${1:-}"
  generator_label="${2:-generated by kao user rewrite}"
  name="${3:-runtime user}"
  role="${4:-operator user}"
  user_id="${5:-}"
  title="${6:-not set}"
  handle="${7:-not set}"
  org="${8:-not set}"

  if [ -z "${env_file}" ]; then
    printf 'ERROR: missing user env file path for write\n' >&2
    return 1
  fi

  mkdir -p "$(dirname "${env_file}")"

  {
    printf '# canonical runtime user source\n'
    printf '# %s\n' "${generator_label}"
    kao_user_state_default_runtime_exports \
      "${name}" \
      "${role}" \
      "${user_id}" \
      "${title}" \
      "${handle}" \
      "${org}"
  } > "${env_file}"
}

kao_user_state_write_runtime_env() {
  local env_file name role user_id title handle org
  env_file="${1:-}"
  name="${2:-runtime user}"
  role="${3:-operator user}"
  user_id="${4:-}"
  title="${5:-not set}"
  handle="${6:-not set}"
  org="${7:-not set}"

  kao_user_state_write_canonical_env \
    "${env_file}" \
    "generated by kao user create" \
    "${name}" \
    "${role}" \
    "${user_id}" \
    "${title}" \
    "${handle}" \
    "${org}"
}

kao_user_resolve_exports() {
  local env_file
  env_file="${1:-}"

  if [ -z "${env_file}" ]; then
    printf 'ERROR: missing user env file path\n' >&2
    return 1
  fi

  if [ ! -f "${env_file}" ]; then
    printf 'ERROR: missing user env file: %s\n' "${env_file}" >&2
    return 1
  fi

  env -i bash -n "${env_file}" >/dev/null 2>&1 || {
    printf 'ERROR: invalid user env syntax: %s\n' "${env_file}" >&2
    return 1
  }

  env -i bash -c '
    set -euo pipefail
    . "$1"

    [ -n "${KAO_USER_NAME:-}" ] || {
      printf "ERROR: missing required field KAO_USER_NAME in %s\n" "$1" >&2
      exit 1
    }

    if [ -z "${KAO_USER_ROLE:-}" ]; then
      KAO_USER_ROLE="operator user"
    fi

    if [ -z "${KAO_USER_ID:-}" ]; then
      slug="$(printf "%s" "${KAO_USER_NAME}" | tr "[:upper:]" "[:lower:]" | tr -cs "a-z0-9" "-")"
      slug="${slug#-}"
      slug="${slug%-}"
      if [ -z "${slug}" ]; then
        slug="unknown"
      fi
      KAO_USER_ID="user-${slug}"
    fi

    if [ -z "${KAO_USER_TITLE:-}" ]; then
      KAO_USER_TITLE="not set"
    fi

    if [ -z "${KAO_USER_HANDLE:-}" ]; then
      KAO_USER_HANDLE="not set"
    fi

    if [ -z "${KAO_USER_ORG:-}" ]; then
      KAO_USER_ORG="not set"
    fi

    export KAO_USER_NAME KAO_USER_ROLE KAO_USER_ID KAO_USER_TITLE KAO_USER_HANDLE KAO_USER_ORG

    python3 - <<'"'"'PY'"'"'
import json
import os

keys = [
    "KAO_USER_NAME",
    "KAO_USER_ROLE",
    "KAO_USER_ID",
    "KAO_USER_TITLE",
    "KAO_USER_HANDLE",
    "KAO_USER_ORG",
]

for key in keys:
    print(f"{key}={json.dumps(os.environ.get(key, ''))}")
PY
  ' _ "${env_file}"
}

kao_user_state_extract_field() {
  local env_file target env_exports key value
  env_file="${1:-}"
  target="${2:-}"

  env_exports="$(kao_user_resolve_exports "${env_file}")" || return 1

  while IFS='=' read -r key value; do
    [ -n "${key}" ] || continue
    if [ "${key}" = "${target}" ]; then
      eval "printf '%s' ${value}"
      return 0
    fi
  done <<EOF_USER_STATE_FIELD
${env_exports}
EOF_USER_STATE_FIELD

  return 1
}

kao_user_state_load_resolved_vars() {
  local env_file env_exports key value
  env_file="${1:-}"

  KAO_USER_RESOLVED_NAME=""
  KAO_USER_RESOLVED_ROLE=""
  KAO_USER_RESOLVED_ID=""
  KAO_USER_RESOLVED_TITLE=""
  KAO_USER_RESOLVED_HANDLE=""
  KAO_USER_RESOLVED_ORG=""

  env_exports="$(kao_user_resolve_exports "${env_file}")" || return 1

  while IFS='=' read -r key value; do
    [ -n "${key}" ] || continue
    case "${key}" in
      KAO_USER_NAME) eval "KAO_USER_RESOLVED_NAME=${value}" ;;
      KAO_USER_ROLE) eval "KAO_USER_RESOLVED_ROLE=${value}" ;;
      KAO_USER_ID) eval "KAO_USER_RESOLVED_ID=${value}" ;;
      KAO_USER_TITLE) eval "KAO_USER_RESOLVED_TITLE=${value}" ;;
      KAO_USER_HANDLE) eval "KAO_USER_RESOLVED_HANDLE=${value}" ;;
      KAO_USER_ORG) eval "KAO_USER_RESOLVED_ORG=${value}" ;;
    esac
  done <<EOF_USER_STATE_EXPORTS
${env_exports}
EOF_USER_STATE_EXPORTS
}

kao_user_inspect_source_kv() {
  local env_file
  env_file="${1:-${KAO_USER_RUNTIME_ENV_FILE:-}}"

  if [ -z "${env_file}" ]; then
    printf 'ERROR: missing user env file path for inspect\n' >&2
    return 1
  fi

  if [ ! -f "${env_file}" ]; then
    printf 'source_state=MISSING\n'
    printf 'runtime_env_file=%s\n' "${env_file}"
    printf 'source_label=missing runtime user\n'
    printf 'source_value=%s\n' "${env_file}"
    return 0
  fi

  if kao_user_state_load_resolved_vars "${env_file}"; then
    printf 'source_state=VALID\n'
    printf 'runtime_env_file=%s\n' "${env_file}"
    printf 'source_label=canonical runtime user\n'
    printf 'source_value=%s\n' "${env_file}"
    printf 'resolved_name=%s\n' "${KAO_USER_RESOLVED_NAME}"
    printf 'resolved_role=%s\n' "${KAO_USER_RESOLVED_ROLE}"
    printf 'resolved_id=%s\n' "${KAO_USER_RESOLVED_ID}"
    printf 'resolved_title=%s\n' "${KAO_USER_RESOLVED_TITLE}"
    printf 'resolved_handle=%s\n' "${KAO_USER_RESOLVED_HANDLE}"
    printf 'resolved_org=%s\n' "${KAO_USER_RESOLVED_ORG}"
    return 0
  fi

  printf 'source_state=INVALID\n'
  printf 'runtime_env_file=%s\n' "${env_file}"
  printf 'source_label=invalid runtime user\n'
  printf 'source_value=%s\n' "${env_file}"
}

kao_user_state_normalize_marker() {
  local raw
  raw="$(printf '%s' "${1:-missing}" | tr -d '\r' | head -n 1)"

  case "${raw}" in
    active|ACTIVE|on|ON|1)
      printf 'active'
      ;;
    inactive|INACTIVE|off|OFF|0|'')
      printf 'inactive'
      ;;
    missing|empty)
      printf 'missing'
      ;;
    *)
      printf 'invalid'
      ;;
  esac
}

kao_user_state_read_raw_marker() {
  if [ -f "${KAO_USER_RUNTIME_STATE_FILE}" ]; then
    tr -d '\r' < "${KAO_USER_RUNTIME_STATE_FILE}" | head -n 1
  else
    printf 'missing'
  fi
}

kao_user_state_write_marker() {
  local marker
  marker="${1:-inactive}"

  mkdir -p "$(dirname "${KAO_USER_RUNTIME_STATE_FILE}")"
  printf '%s\n' "${marker}" > "${KAO_USER_RUNTIME_STATE_FILE}"
}

kao_user_state_runtime_diff_count() {
  local current_file snapshot_file field current_value snapshot_value count
  current_file="${1:-}"
  snapshot_file="${2:-}"
  count=0

  [ -f "${current_file}" ] || {
    printf '0'
    return 0
  }

  [ -f "${snapshot_file}" ] || {
    printf '0'
    return 0
  }

  for field in KAO_USER_NAME KAO_USER_ROLE KAO_USER_ID KAO_USER_TITLE KAO_USER_HANDLE KAO_USER_ORG; do
    current_value="$(kao_user_state_extract_field "${current_file}" "${field}" 2>/dev/null || true)"
    snapshot_value="$(kao_user_state_extract_field "${snapshot_file}" "${field}" 2>/dev/null || true)"
    if [ "${current_value}" != "${snapshot_value}" ]; then
      count=$((count + 1))
    fi
  done

  printf '%s' "${count}"
}

kao_user_state_sync_mode() {
  local diff_count
  diff_count="${1:-0}"

  case "${diff_count}" in
    0) printf 'CURRENT' ;;
    *) printf 'MODIFIED_SINCE_ACTIVATION' ;;
  esac
}

kao_user_state_sync_hint() {
  local diff_count
  diff_count="${1:-0}"

  case "${diff_count}" in
    0) printf 'none' ;;
    *) printf 'run kao user diff or kao user activate again' ;;
  esac
}

kao_user_create_runtime_source() {
  local name role user_id title handle org result_state policy_state create_action
  name="${1:-runtime user}"
  role="${2:-operator user}"
  user_id="${3:-}"
  title="${4:-not set}"
  handle="${5:-not set}"
  org="${6:-not set}"

  kao_user_state_require_context || return 1
  mkdir -p "${KAO_USER_ENV_DIR}"

  kao_user_state_write_runtime_env \
    "${KAO_USER_RUNTIME_ENV_FILE}" \
    "${name}" \
    "${role}" \
    "${user_id}" \
    "${title}" \
    "${handle}" \
    "${org}"

  if [ ! -f "${KAO_USER_RUNTIME_STATE_FILE}" ]; then
    kao_user_state_write_marker inactive
    result_state="AVAILABLE"
  else
    case "$(kao_user_state_normalize_marker "$(kao_user_state_read_raw_marker)")" in
      active) result_state="ACTIVE" ;;
      *) result_state="AVAILABLE" ;;
    esac
  fi

  policy_state="SUCCESS"
  create_action="created-runtime-source"
  kao_user_state_log "user.create | action=${create_action} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'create_action=%s\n' "${create_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_state_file=%s\n' "${KAO_USER_RUNTIME_STATE_FILE}"
}

kao_user_remove_runtime_source() {
  local result_state policy_state remove_action env_existed state_existed snapshot_existed

  kao_user_state_require_context || return 1

  policy_state="NOOP"
  remove_action="none"
  result_state="INACTIVE"
  env_existed=0
  state_existed=0
  snapshot_existed=0

  mkdir -p "${KAO_USER_ENV_DIR}"

  if [ -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then env_existed=1; fi
  if [ -f "${KAO_USER_RUNTIME_STATE_FILE}" ]; then state_existed=1; fi
  if [ -f "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}" ]; then snapshot_existed=1; fi

  rm -f \
    "${KAO_USER_RUNTIME_ENV_FILE}" \
    "${KAO_USER_RUNTIME_STATE_FILE}" \
    "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"

  if [ "${env_existed}" -eq 1 ] || [ "${state_existed}" -eq 1 ] || [ "${snapshot_existed}" -eq 1 ]; then
    policy_state="SUCCESS"
    remove_action="removed-runtime-source-state-and-snapshot"
  fi

  kao_user_state_log "user.remove | action=${remove_action} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'remove_action=%s\n' "${remove_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_state_file=%s\n' "${KAO_USER_RUNTIME_STATE_FILE}"
  printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
}

kao_user_activate_runtime_source() {
  local policy_state activation_action result_state

  kao_user_state_require_context || return 1
  mkdir -p "${KAO_USER_ENV_DIR}"

  if [ ! -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    printf 'policy_state=DENY\n'
    printf 'activation_action=missing-runtime-source\n'
    printf 'result_state=INACTIVE\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 1
  fi

  if ! kao_user_state_load_resolved_vars "${KAO_USER_RUNTIME_ENV_FILE}"; then
    printf 'policy_state=DENY\n'
    printf 'activation_action=invalid-runtime-source\n'
    printf 'result_state=INVALID\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 1
  fi

  kao_user_state_write_marker active
  cp "${KAO_USER_RUNTIME_ENV_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"

  policy_state="SUCCESS"
  activation_action="activated-runtime-source"
  result_state="ACTIVE"

  kao_user_state_log "user.activate | action=${activation_action} | result_state=${result_state} | user_id=${KAO_USER_RESOLVED_ID}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'activation_action=%s\n' "${activation_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_state_file=%s\n' "${KAO_USER_RUNTIME_STATE_FILE}"
  printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
}

kao_user_deactivate_runtime_source() {
  local policy_state deactivation_action result_state

  kao_user_state_require_context || return 1
  mkdir -p "${KAO_USER_ENV_DIR}"

  if [ ! -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    rm -f "${KAO_USER_RUNTIME_STATE_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
    printf 'policy_state=NOOP\n'
    printf 'deactivation_action=missing-runtime-source\n'
    printf 'result_state=INACTIVE\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 0
  fi

  kao_user_state_write_marker inactive
  rm -f "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"

  policy_state="SUCCESS"
  deactivation_action="deactivated-runtime-source"
  result_state="AVAILABLE"

  kao_user_state_log "user.deactivate | action=${deactivation_action} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'deactivation_action=%s\n' "${deactivation_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_state_file=%s\n' "${KAO_USER_RUNTIME_STATE_FILE}"
  printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
}

kao_user_recover_runtime_state() {
  local result_state policy_state repair_action marker_normalized

  kao_user_state_require_context || return 1

  result_state="INACTIVE"
  policy_state="NOOP"
  repair_action="none"

  mkdir -p "${KAO_USER_ENV_DIR}"

  if [ -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    if kao_user_resolve_exports "${KAO_USER_RUNTIME_ENV_FILE}" >/dev/null 2>&1; then
      marker_normalized="$(kao_user_state_normalize_marker "$(kao_user_state_read_raw_marker)")"

      case "${marker_normalized}" in
        active)
          kao_user_state_write_marker active
          cp "${KAO_USER_RUNTIME_ENV_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
          result_state="ACTIVE"
          policy_state="SUCCESS"
          repair_action="normalized-active-marker"
          ;;
        inactive|missing)
          kao_user_state_write_marker inactive
          rm -f "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
          result_state="AVAILABLE"
          policy_state="SUCCESS"
          repair_action="normalized-inactive-marker"
          ;;
        invalid)
          kao_user_state_write_marker inactive
          rm -f "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
          result_state="AVAILABLE"
          policy_state="SUCCESS"
          repair_action="replaced-invalid-marker-with-inactive"
          ;;
      esac
    else
      rm -f "${KAO_USER_RUNTIME_STATE_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
      result_state="INVALID"
      policy_state="PARTIAL"
      repair_action="removed-broken-state-marker-invalid-env-remains"
    fi
  else
    rm -f "${KAO_USER_RUNTIME_STATE_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
    result_state="INACTIVE"
    policy_state="SUCCESS"
    repair_action="removed-orphan-state-marker"
  fi

  kao_user_state_log "user.recover | action=${repair_action} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'repair_action=%s\n' "${repair_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_state_file=%s\n' "${KAO_USER_RUNTIME_STATE_FILE}"
  printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
}

kao_user_patch_runtime_source() {
  local input_field normalized_field new_value current_env
  local name role user_id title handle org policy_state patch_action result_state
  input_field="${1:-}"
  new_value="${2:-}"

  kao_user_state_require_context || return 1

  if [ ! -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    printf 'policy_state=DENY\n'
    printf 'patch_action=missing-runtime-source\n'
    printf 'result_state=INACTIVE\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 1
  fi

  normalized_field="$(kao_user_state_normalize_field_name "${input_field}")"

  if ! kao_user_state_is_allowed_field "${normalized_field}"; then
    printf 'policy_state=DENY\n'
    printf 'patch_action=forbidden-field\n'
    printf 'result_state=INVALID\n'
    printf 'field=%s\n' "${normalized_field}"
    return 1
  fi

  kao_user_state_load_resolved_vars "${KAO_USER_RUNTIME_ENV_FILE}" || {
    printf 'policy_state=DENY\n'
    printf 'patch_action=invalid-runtime-source\n'
    printf 'result_state=INVALID\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 1
  }

  name="${KAO_USER_RESOLVED_NAME}"
  role="${KAO_USER_RESOLVED_ROLE}"
  user_id="${KAO_USER_RESOLVED_ID}"
  title="${KAO_USER_RESOLVED_TITLE}"
  handle="${KAO_USER_RESOLVED_HANDLE}"
  org="${KAO_USER_RESOLVED_ORG}"

  case "${normalized_field}" in
    KAO_USER_NAME) name="${new_value}" ;;
    KAO_USER_ROLE) role="${new_value}" ;;
    KAO_USER_ID) user_id="${new_value}" ;;
    KAO_USER_TITLE) title="${new_value}" ;;
    KAO_USER_HANDLE) handle="${new_value}" ;;
    KAO_USER_ORG) org="${new_value}" ;;
  esac

  current_env="$(mktemp)"
  cp "${KAO_USER_RUNTIME_ENV_FILE}" "${current_env}"

  if ! kao_user_state_write_canonical_env \
    "${KAO_USER_RUNTIME_ENV_FILE}" \
    "generated by kao user patch" \
    "${name}" \
    "${role}" \
    "${user_id}" \
    "${title}" \
    "${handle}" \
    "${org}"; then
    cp "${current_env}" "${KAO_USER_RUNTIME_ENV_FILE}"
    rm -f "${current_env}"
    printf 'policy_state=ERROR\n'
    printf 'patch_action=write-failed\n'
    printf 'result_state=INVALID\n'
    return 1
  fi

  rm -f "${current_env}"

  case "$(kao_user_state_normalize_marker "$(kao_user_state_read_raw_marker)")" in
    active) result_state="ACTIVE" ;;
    *) result_state="AVAILABLE" ;;
  esac

  policy_state="SUCCESS"
  patch_action="patched-runtime-source"

  kao_user_state_log "user.patch | action=${patch_action} | field=${normalized_field} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'patch_action=%s\n' "${patch_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'field=%s\n' "${normalized_field}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
}

kao_user_update_runtime_source() {
  local assignment field value
  local policy_state result_state update_count

  kao_user_state_require_context || return 1

  if [ "$#" -eq 0 ]; then
    printf 'policy_state=DENY\n'
    printf 'update_action=no-fields-provided\n'
    printf 'result_state=INVALID\n'
    return 1
  fi

  update_count=0

  for assignment in "$@"; do
    field="${assignment%%=*}"
    value="${assignment#*=}"

    if [ "${assignment}" = "${field}" ]; then
      printf 'policy_state=DENY\n'
      printf 'update_action=invalid-assignment\n'
      printf 'result_state=INVALID\n'
      printf 'assignment=%s\n' "${assignment}"
      return 1
    fi

    kao_user_patch_runtime_source "${field}" "${value}" >/dev/null || {
      printf 'policy_state=DENY\n'
      printf 'update_action=patch-failed\n'
      printf 'result_state=INVALID\n'
      printf 'assignment=%s\n' "${assignment}"
      return 1
    }

    update_count=$((update_count + 1))
  done

  case "$(kao_user_state_normalize_marker "$(kao_user_state_read_raw_marker)")" in
    active) result_state="ACTIVE" ;;
    *) result_state="AVAILABLE" ;;
  esac

  policy_state="SUCCESS"
  kao_user_state_log "user.update | action=updated-runtime-source | update_count=${update_count} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'update_action=updated-runtime-source\n'
  printf 'update_count=%s\n' "${update_count}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
}

kao_user_rewrite_runtime_source() {
  local result_state policy_state rewrite_action

  kao_user_state_require_context || return 1

  if [ ! -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    printf 'policy_state=DENY\n'
    printf 'rewrite_action=missing-runtime-source\n'
    printf 'result_state=INACTIVE\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 1
  fi

  kao_user_state_load_resolved_vars "${KAO_USER_RUNTIME_ENV_FILE}" || {
    printf 'policy_state=DENY\n'
    printf 'rewrite_action=invalid-runtime-source\n'
    printf 'result_state=INVALID\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 1
  }

  kao_user_state_write_canonical_env \
    "${KAO_USER_RUNTIME_ENV_FILE}" \
    "rewritten by kao user rewrite" \
    "${KAO_USER_RESOLVED_NAME}" \
    "${KAO_USER_RESOLVED_ROLE}" \
    "${KAO_USER_RESOLVED_ID}" \
    "${KAO_USER_RESOLVED_TITLE}" \
    "${KAO_USER_RESOLVED_HANDLE}" \
    "${KAO_USER_RESOLVED_ORG}"

  case "$(kao_user_state_normalize_marker "$(kao_user_state_read_raw_marker)")" in
    active) result_state="ACTIVE" ;;
    *) result_state="AVAILABLE" ;;
  esac

  policy_state="SUCCESS"
  rewrite_action="rewritten-runtime-source"

  kao_user_state_log "user.rewrite | action=${rewrite_action} | result_state=${result_state}"

  printf 'policy_state=%s\n' "${policy_state}"
  printf 'rewrite_action=%s\n' "${rewrite_action}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
}

kao_user_diff_runtime_source_kv() {
  local diff_count sync_mode sync_hint field current_value snapshot_value

  kao_user_state_require_context || return 1

  if [ ! -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    printf 'diff_state=MISSING_SOURCE\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 0
  fi

  if ! kao_user_state_load_resolved_vars "${KAO_USER_RUNTIME_ENV_FILE}"; then
    printf 'diff_state=INVALID_SOURCE\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    return 0
  fi

  if [ ! -f "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}" ]; then
    printf 'diff_state=NO_ACTIVE_SNAPSHOT\n'
    printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
    printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
    return 0
  fi

  diff_count="$(kao_user_state_runtime_diff_count "${KAO_USER_RUNTIME_ENV_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}")"
  sync_mode="$(kao_user_state_sync_mode "${diff_count}")"
  sync_hint="$(kao_user_state_sync_hint "${diff_count}")"

  printf 'diff_state=READY\n'
  printf 'diff_count=%s\n' "${diff_count}"
  printf 'sync_mode=%s\n' "${sync_mode}"
  printf 'sync_hint=%s\n' "${sync_hint}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"

  for field in KAO_USER_NAME KAO_USER_ROLE KAO_USER_ID KAO_USER_TITLE KAO_USER_HANDLE KAO_USER_ORG; do
    current_value="$(kao_user_state_extract_field "${KAO_USER_RUNTIME_ENV_FILE}" "${field}" 2>/dev/null || true)"
    snapshot_value="$(kao_user_state_extract_field "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}" "${field}" 2>/dev/null || true)"
    if [ "${current_value}" != "${snapshot_value}" ]; then
      printf 'changed_%s_active=%s\n' "$(printf '%s' "${field}" | tr '[:upper:]' '[:lower:]')" "${snapshot_value}"
      printf 'changed_%s_current=%s\n' "$(printf '%s' "${field}" | tr '[:upper:]' '[:lower:]')" "${current_value}"
    fi
  done
}

kao_user_emit_state_kv() {
  local state_raw marker_normalized state_mode state_label state_relation result_state activation_hint
  local source_label source_value recover_hint broken_reason diff_count sync_mode sync_hint

  kao_user_state_require_context || return 1

  state_raw="missing"
  marker_normalized="missing"
  state_mode="inactive"
  state_label="runtime user inactive"
  state_relation="owner primary only"
  result_state="INACTIVE"
  activation_hint="create ${KAO_USER_RUNTIME_ENV_FILE} then activate explicitly"
  recover_hint="none"
  broken_reason="none"

  source_label="placeholder"
  source_value="no runtime user source"
  diff_count="0"
  sync_mode="NO_ACTIVE_SNAPSHOT"
  sync_hint="activate user to create a runtime snapshot"

  if [ -f "${KAO_USER_RUNTIME_STATE_FILE}" ]; then
    state_raw="$(kao_user_state_read_raw_marker)"
    if [ -z "${state_raw}" ]; then
      state_raw="empty"
    fi
  fi

  marker_normalized="$(kao_user_state_normalize_marker "${state_raw}")"

  if [ -f "${KAO_USER_RUNTIME_ENV_FILE}" ]; then
    if kao_user_resolve_exports "${KAO_USER_RUNTIME_ENV_FILE}" >/dev/null 2>&1; then
      source_label="canonical runtime user"
      source_value="${KAO_USER_RUNTIME_ENV_FILE}"

      case "${marker_normalized}" in
        active)
          state_mode="active"
          state_label="runtime user explicitly activated"
          state_relation="runtime source active"
          result_state="ACTIVE"
          activation_hint="none"
          recover_hint="none"
          if [ -f "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}" ]; then
            diff_count="$(kao_user_state_runtime_diff_count "${KAO_USER_RUNTIME_ENV_FILE}" "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}")"
            sync_mode="$(kao_user_state_sync_mode "${diff_count}")"
            sync_hint="$(kao_user_state_sync_hint "${diff_count}")"
          fi
          ;;
        inactive)
          state_mode="available"
          state_label="runtime user explicitly inactive"
          state_relation="runtime source available but inactive"
          result_state="AVAILABLE"
          activation_hint="run kao user activate"
          recover_hint="none"
          ;;
        missing)
          state_mode="available"
          state_label="runtime source available"
          state_relation="runtime source available but inactive"
          result_state="AVAILABLE"
          activation_hint="run kao user activate"
          recover_hint="none"
          ;;
        invalid)
          state_mode="broken"
          state_label="runtime activation marker invalid"
          state_relation="runtime source valid but activation marker corrupted"
          result_state="BROKEN"
          activation_hint="run kao user recover"
          recover_hint="run kao user recover"
          broken_reason="invalid state marker"
          ;;
      esac
    else
      source_label="invalid runtime user"
      source_value="${KAO_USER_RUNTIME_ENV_FILE}"
      state_mode="invalid"
      state_label="runtime user source invalid"
      state_relation="runtime source unreadable"
      result_state="INVALID"
      activation_hint="fix runtime source or remove it"
      recover_hint="run kao user inspect or kao user remove"
      broken_reason="invalid runtime source"
      sync_mode="INVALID_SOURCE"
      sync_hint="rewrite or remove invalid runtime source"
    fi
  else
    source_label="missing runtime user"
    source_value="${KAO_USER_RUNTIME_ENV_FILE}"
  fi

  printf 'state_mode=%s\n' "${state_mode}"
  printf 'state_label=%s\n' "${state_label}"
  printf 'state_relation=%s\n' "${state_relation}"
  printf 'result_state=%s\n' "${result_state}"
  printf 'source_label=%s\n' "${source_label}"
  printf 'source_value=%s\n' "${source_value}"
  printf 'activation_hint=%s\n' "${activation_hint}"
  printf 'recover_hint=%s\n' "${recover_hint}"
  printf 'broken_reason=%s\n' "${broken_reason}"
  printf 'runtime_env_file=%s\n' "${KAO_USER_RUNTIME_ENV_FILE}"
  printf 'runtime_state_file=%s\n' "${KAO_USER_RUNTIME_STATE_FILE}"
  printf 'runtime_active_snapshot_file=%s\n' "${KAO_USER_RUNTIME_ACTIVE_SNAPSHOT_FILE}"
  printf 'sync_mode=%s\n' "${sync_mode}"
  printf 'sync_hint=%s\n' "${sync_hint}"
  printf 'diff_count=%s\n' "${diff_count}"
}
